name: CI

on:
  deployment:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo '${{ github.event.deployment.ref }}'
