name: CI

env:
  test: 1

on: [deployment]

jobs:
  build:
    if: github.event.deployment.environment == 'testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/echo
