name: CI

on:
  deployment:
    target: testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ${{ github.event.deployment }} > dump
    - name: Cat
      run: cat dump
