name: CI

env:
  test: 1

on: [deployment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: To Production
        if: github.event.deployment.environment == 'production'
        run: echo ${{ github.event.deployment.ref }} on PRODUCTION
      - name: To Testing
        if: github.event.deployment.environment == 'testing'
        run: echo ${{ toJson(github.event) }}
